[project]
name = "odia-ai-educational-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "google-cloud-vision>=3.12.1",
    "numpy<2",
    "paddleocr==2.7.0.3",
    "paddlepaddle==2.6.2",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "pymupdf==1.20.2",
    "setuptools>=69",
    "tqdm>=4.67.3",
]
