from app.prompts.prompts import (
    CONVERSATIONAL_SYSTEM_PROMPT,
    EDUCATIONAL_SYSTEM_PROMPT,
    INTENT_ROUTER_SYSTEM_PROMPT,
)

__all__ = [
    "CONVERSATIONAL_SYSTEM_PROMPT",
    "EDUCATIONAL_SYSTEM_PROMPT",
    "INTENT_ROUTER_SYSTEM_PROMPT",
]
